# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: vidquick_development

test:
  <<: *default
  database: vidquick_test

production:
  <<: *default
  database: vidquick_production
  username: vidquick
  password: <%= ENV['VIDQUICK_DATABASE_PASSWORD'] %>
